# ETL - Dados de ações Índice Bovespa

#### Importando bibliotecas

```{r}
library(yfR)
library(plyr)
library(dplyr)
library(ggplot2)
```

#### Extração de dados

```{r include=FALSE}
#extraindo 1 ano de dados de ações

ibov<-yf_collection_get('IBOV',
                        first_date = Sys.Date() - 365,
                        last_date = Sys.Date())
```

#### Manipulando dados extraídos

```{r}
# dividindo o dataframe
acoes<-dlply(ibov, .(ticker), function(x){rownames(x)=x$row; x$row=NULL; x})

# filtrando colunas - iniciando pelo primeiro dataset
dados_acoes<-acoes[[1]][,c(2,8)]

# mudando nomes das colunas e adicionando ticker a coluna preço
colnames(dados_acoes)<-c("Data",paste("Preço", acoes[[1]][8,1]))

# iterando em loop para novo dataset
for (i in 2:83){
  dados_acoes_loop <- acoes[[i]][,c(2,8)]
  colnames(dados_acoes_loop)<-c("Data",paste("Preço", acoes[[i]][8,1]))
  dados_acoes<-merge(dados_acoes,dados_acoes_loop, by = "Data")}
```

#### Visualizando dados

```{r}
# gerando graficos com exemplos de acoes
bancos<-ggplot()+
  geom_line(data=dados_acoes, aes(x = Data, y = `Preço BBAS3.SA` , color ="Banco do Brasil"))+
  geom_line(data=dados_acoes, aes(x = Data, y = `Preço BBDC4.SA` , color ="Bradesco"))+
  geom_line(data=dados_acoes, aes(x = Data, y = `Preço ITUB4.SA` , color ="Itaú"))+
  geom_line(data=dados_acoes, aes(x = Data, y = `Preço SANB11.SA` , color ="Santander"))+
  
  xlab("Data")+
  ylab("Preço")+
  labs(color="Bancos")

# plot
print(bancos)
```
